import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 text-lg">
          <Link href="/" className="m-4">Home</Link>
          <Link href="/a" className="m-4">Page without tabs</Link>
          <Link href="/b" className="m-4">Page with tabs</Link>
        </nav>
        <div className="flex min-h-screen items-start justify-center bg-zinc-50 font-sans dark:bg-black">
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
